name: ML Model Deployment with SageMaker

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

env:
  TF_DIR: terraform

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      train: ${{ steps.filter.outputs.train }}
      smoke: ${{ steps.filter.outputs.smoke }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Detect file changes with dorny/paths-filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            train:
              - 'model/train_model.py'
              - 'infra/**'
            smoke:
              - 'test/smoke_test_inference.py'

  deploy:
    needs: detect-changes
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
    environment: ml-sagemaker-deploy

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init with S3 Backend
        working-directory: ${{ env.TF_DIR }}
        run: terraform init -reconfigure

      - name: Export Terraform outputs to GitHub Actions env
        working-directory: ${{ env.TF_DIR }}
        run: |
          echo "S3_BUCKET=$(terraform output -raw s3_bucket_name)" >> $GITHUB_ENV
          echo "SAGEMAKER_ENDPOINT_NAME=$(terraform output -raw sagemaker_endpoint_name)" >> $GITHUB_ENV
          echo "API_GATEWAY_URL=$(terraform output -raw inference_api_url)" >> $GITHUB_ENV

      - name: Conditionally Train and Deploy Model
        run: |
          echo "Training and deploying model due to changes in train_model.py"
          python model/train_model.py
          python infra/upload_model_to_s3.py

          
      - name: Conditionally Deploy Inference Proxy (Lambda + API Gateway)
        working-directory: ${{ env.TF_DIR }}
        run: |
          echo "Packaging Lambda function with dependencies"
          mkdir -p ../build
          pip install -r ../lambda/requirements.txt -t ../build/
          cp ../lambda/inference_lambda.py ../build/
          cd ../build
          zip -r ../lambda_package.zip .
          mv ../lambda_package.zip ../terraform/
          cd ../terraform
          terraform apply -auto-approve

      - name: Conditionally Load Test SageMaker Endpoint
        run: |
          echo "Running load test"
          python test/load_test_sagemaker.py

      - name: Conditionally Run Inference Smoke Test
        if: needs.detect-changes.outputs.smoke == 'true'
        run: |
          echo "Running smoke test due to changes in smoke_test_inference.py"
          python test/smoke_test_inference.py
