name: ML Model Deployment with SageMaker

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:  # Allows manual triggering

env:
  TF_DIR: terraform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ml-sagemaker-deploy  # Define GitHub Environment

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python Dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Terraform Init with S3 Backend
      working-directory: ${{ env.TF_DIR }}
      run: terraform init -reconfigure

    - name: Terraform Apply
      working-directory: ${{ env.TF_DIR }}
      run: |
        terraform apply -auto-approve \
          -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
    
    - name: Debug Terraform Output
      working-directory: ${{ env.TF_DIR }}
      run: |
        terraform output -json
    - name: Use Outputs
      working-directory: ${{ env.TF_DIR }}
      run: |
        echo "Bucket: $S3_BUCKET_NAME"
        echo "Role: $SAGEMAKER_EXECUTION_ROLE_ARN"
        echo "Region: $AWS_REGION"
    - name: Export Terraform Outputs to ENV
      working-directory: ${{ env.TF_DIR }}
      shell: bash
      run: |
        BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null | tr -d '\r')
        ROLE=$(terraform output -raw sagemaker_execution_role_arn 2>/dev/null | tr -d '\r')
        REGION=$(terraform output -raw region 2>/dev/null | tr -d '\r')

        echo "S3_BUCKET_NAME=$BUCKET" >> $GITHUB_ENV
        echo "SAGEMAKER_EXECUTION_ROLE_ARN=$ROLE" >> $GITHUB_ENV
        echo "AWS_REGION=$REGION" >> $GITHUB_ENV

        # Debug print for this step only
        echo "Sanity Check in Export Step:"
        echo "Bucket: $BUCKET"
        echo "Role: $ROLE"
        echo "Region: $REGION"
    - name: Print Exported Environment Variables
      run: |
        echo "Bucket: $S3_BUCKET_NAME"
        echo "Role: $SAGEMAKER_EXECUTION_ROLE_ARN"
        echo "Region: $AWS_REGION"



    # - name: Train Model
    #   run: python model/train_model.py

    # - name: Upload Model to S3
    #   run: python infra/upload_model_to_s3.py

    # - name: Deploy Model to SageMaker
    #   run: python infra/deploy_model_to_sagemaker.py

    # - name: Inference Smoke Test
    #   run: python test/smoke_test_inference.py
